language: java
os: linux
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw

branches:
  only:
    - travis-ci

cache:
  directories:
    - $home/.m2
stages:
  - tests
  - build
jobs:
  include:
    - stage: tests             # naming the Tests stage
      script: mvnw  test
    - stage: build
      script: mvnw  install

